### PR TITLE
Private Events

### PR DESCRIPTION
**Pull request by taiwo2**
Built with

- Ruby
- Ruby on Rails
- HTML
- SASS
- Bulma
- run bundle install
- run yarn install
- run ruby ./bin/webpack-dev-server  before run the app

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello Team, great work you've done so far on this project. However, there are still a few more improvements to make in order to get it approved 😊🙏

- [x] When I first visit the user show page (profile) I get an error of undefined current_user method. Kindly create that method in the helpers and include it within the controller files you want to use it inside.
- [ ] The User model has to have proper associations with the events using correct foreign keys and class names.
user_assoc_requirement Consider using ```creator_id``` as foreign key or in your case it's ```host_id```

- [ ] In your Event and User model you've used ```attendees``` and ```attended_events``` terms but you never specified them in the Invitation model. Please use the proper foreign keys and class names i.e. 
```
# Invitation model

belongs_to :attendee, class_name: "User"
belongs_to :attended_event, class_name: "Event"
```

- [ ] Kindly use the scopes you created within the index method of your events controller, not directly into the views i.e. ```@past_events = @events.past```
- [ ] Please remove any logic from the views and use your helpers for that matter.
- [ ] Kindly write a more descriptive PR summary in order to make it professional and easier to understand what you've done on the project.

<hr>

Good luck and happy coding 👨‍💻💻

**Review by MarilenaRoque — CHANGES_REQUESTED** [review]
## Hello @taiwo2! :rocket:

Congrats on the effort to implement the changes requested. :clap:
However, we still need to fix some features to get your approval.

## Changes Required ♻️ 

- [x] Your current_user is still not available on your controllers. When I try to create a new event, it raises an error because the current_user is not defined. 

( Error message: undefined local variable or method `current_user' for #<EventsController:0x0000000000b130>)
**Hints:** You can make a current_user method inside your application controller to return the user, using the session info. Your association for user and events are not following name patterns. You say that the events belong to :host, but you called the foreign key user_id, instead of :host_id. Be consistent with the names will help you.

- [ ] Seems like your past and upcoming scopes are well implemented but your events are not displaying in the correct place on the page.
- [ ] Your 'attend' feature is not working. Every time I try to attend an event it fails to be saved.
- [ ] Please modify your PR, as requested by my teammate, to have a summary of your project and keep your commit messages descriptive.

## To Highlight 🌟 

- Your UI looks awesome!

Any further questions? Please, contact me on Slack.** 

Keep going with the hard work! 💪🏻 
Happy Coding! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello again team, I can see the effort you've put into improving the project. Well done. However, there are still a few more changes to make 😊🙏

- [ ] ```SQLite3::SQLException: no such column: event_date``` This error is raising on the root page defining that the events table has no such a column called "event_date" (Please check your schema and look for the column related to the date and then use it in your scopes) Hint: "Next time, you don't have to create a specific column to calculate the date because rails is creating "created_at" column for each table/model type by default".
- [ ] ```SQLite3::SQLException: no such column: events.creator_id``` This is an error raising up when I try visiting the user show page (Currently you don't have any related column in the events table called "creator_id") Kindly fix this issue and use the existing column which is "user_id". If you want to use the "creator_id" you'll have to modify your migrations and use foreign_key and class name.
- [ ] You've defined the ```current_user``` method but the controllers you used that method in still don't know where to find it. Kindly include the SessionsHelper that involve the ```current_user``` method at the top of those controllers files i.e. ```include SessionsHelper```

<hr>

Kindly do the above changes and make sure you're not facing any errors before you submit for another review.
Good luck and happy coding 👨‍💻💻

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Congratulations on completing your project. Your UI looks great.

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
